### ISSUE TITLE
[Question] http call

### ISSUE THREAD

**Issue by Madrity** [testinggospels/camouflage#123]
Hello, 

Can we create expectation by http call ? And Do you plan to provide a client like "mockserver-client" ?

Thx.

**Comment by shubhendumadhukar** [comment]
@Madrity
Camouflage is not built to be used as a library. It can be considered similar to wiremock's standalone server. You install it as a global npm package and run it via cli and a config file.

As of now, there is no plan to build a client, but if you could provide a specific use case where you might need a client, we'll definitely consider building it.

**Comment by Madrity** [comment]
Ok thanks !

Currently, I create the expectation for each features test during the test, this is litteraly my "Given" part (gherkin approach).
