### ISSUE TITLE
More examples how to use "assign" Customer Helper in the Documentation

### ISSUE THREAD

**Issue by dgrafova** [testinggospels/camouflage#173]
I didn't find any description or code example in the documentation how to get a value of a variable which is defined using the "assign" customer helper inside the {{#code}}.

For example, i want to use the productIds from the request query ("?productIds=123,234,345") and split it inside the {{#code}} block. 
The following solution has worked for me, but i don't think it is a proper way to get the value from the "context.data.root.productsId" (found in the code base on [github](https://github.com/testinggospels/camouflage/blob/develop/src/handlebar/AssignHelper.ts)).

```
{{assign name='productIds' value=(capture from="query" key="productIds") }} 
...
{{#code}}
(()=>{
   function getProductIdsAsArray() {
   const productIds = context.data.root.productIds;
   const productIdsArray = productIds.split(',');
   return productIdsArray;
   ...
}
```

It would be great to get more examples, how to get the assigned values not only inside {{#pg}}, but also {{#code}}.

**Comment by shubhendumadhukar** [comment]
Since you're already inside a `code` helper. You can assign a variable by simply using Javascript code. All helpers have access to the `request` object so your code might look something like following:
```
{{#code}}
(()=>{
   function getProductIdsAsArray() {
   const productIds = request.query.productIds;
   const productIdsArray = productIds.split(',');
   return productIdsArray;
   ...
}
{{/code}}
```

**Comment by dgrafova** [comment]
Thank you  @shubhendumadhukar for your answer. But what if i want to use assign, in order to define a const variable, which i'm going to use inside multiple {{#inject}}.
For example:
`
{{assign name='MINUTES_PER_DAY' value=1440 }}
...

{
    "startTime": {{#inject}}(()=>{ return moment().utcOffset(MINUTES_PER_DAY) ); })();{{/inject}}
    "endTime": {{#inject}}(()=>{ return moment().utcOffset(MINUTES_PER_DAY + 2*60) ); })();{{/inject}}
}`

do i need to use "context.data.root.MINUTES_PER_DAY" in this case?

**Comment by shubhendumadhukar** [comment]
Ideally it should work, because that's how `assign` helper creates variables.

https://github.com/testinggospels/camouflage/blob/7638a82c8004d9f8efc727570f88319c911fa242/src/handlebar/AssignHelper.ts#L22

However, I'd have to run some test to confirm my assumption.

**Comment by shubhendumadhukar** [comment]
UPDATE: Tested the following mock and our assumptions holds

```javascript
{{assign name='MINUTES_PER_DAY' value=1440 }}
HTTP/1.1 200 OK
X-Requested-By: Shubhendu Madhukar
Content-Type: application/json

{
    "phone": {{#inject}}(()=>{ return context.data.root.MINUTES_PER_DAY })();{{/inject}}
}
```

**Comment by dgrafova** [comment]
Great, thank you @shubhendumadhukar !
