### ISSUE TITLE
Request matcher not working on grpc

### ISSUE THREAD

**Issue by elpadrinoIV** [testinggospels/camouflage#193]
**Describe the bug**
Trying to match with `is` + `capture` doesn't work

**To Reproduce**
1. Tree structure:
```
./mocks
    |- /test
        |- Greeter
             |- SayHello.mock
./protos
    |- simple.proto
./config.yml
```
2. File content:
```
// simple.proto
syntax = "proto3";

package test;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply);
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 1;
}
```

```
// SayHello.mock
{{#is (capture using='jsonpath' selector='$.name') 'Bob' }}
{
  "message": "{{capture using='jsonpath' selector='$.name'}}"
}
{{else}}
{
  "message": "Not Bob, you are: {{capture using='jsonpath' selector='$.name'}}"
}
{{/is}}
```
```
// config.yml
...
  grpc:
    enable: true
    #host: localhost
    host: 0.0.0.0
    port: 4312
    mocks_dir: "./mocks"
    protos_dir: "./protos"
    grpc_tls: false
```
3. Run camouflage: `docker run -d -p 4312:4312  -v $(pwd):/app --name camouflage shubhendumadhukar/camouflage`
4. Hit endpoint with `Bob`:
```
grpcurl \
  -proto protos/simple.proto \
  -d '{"name": "Bob"}' \
  -plaintext \
  localhost:4312 \
  test.Greeter/SayHello
{
  "message": "Not Bob, you are: Bob"
}
```
5. Hit endpoint with `Alice`:
```
grpcurl \
  -proto protos/simple.proto \
  -d '{"name": "Alice"}' \
  -plaintext \
  localhost:4312 \
  test.Greeter/SayHello
{
  "message": "Not Bob, you are: Alice"
}
```
**Expected behavior**
Step 4 should print a different message: `{ "message": "Bob" }`.

The jsonpath is correct, because when returning the message, it correctly says "you are: Bob". However, the comparison doesn't seem to be working.

**Additional context**
```
2022-09-30 15:07:53 debug: Unary Request: {"name":"Bob"}
2022-09-30 15:07:53 debug: Mock file path: mocks/test/Greeter/SayHello.mock
2022-09-30 15:07:53 debug: Response: {
  "message": "Not Bob, you are: Bob"
}
```

**Comment by elpadrinoIV** [comment]
Hello!
Any updates or ETA on this?

Thanks!

**Comment by twbecker** [comment]
So given this bug, is there any way to return different mock responses for the same API based on request parameters?

**Comment by elpadrinoIV** [comment]
I think there's always the option to run arbitrary code (end of this section: https://testinggospels.github.io/camouflage/request-matching/).
I haven't tried it yet, though

**Comment by shubhendumadhukar** [comment]
Apologies for the delay in response. I have been occupied elsewhere and had only been looking at pull reqeusts.

I have however look into the issue. TLDR; Use regex instead of jsonpath as an interim solution.

Explanation:
1. Capture helper: It seems like if we use `jsonpath` to capture a value, the type of value is `object`.
2. Is helper: The comparison takes into account the types of the values being compared.
3. Why the results are unexpected?
    a. The left hand side value i.e. `(capture using='jsonpath' selector='$.name')` has a type of `object`
    b. The right hand side value i.e. 'Bob' has a type of `string`
    c. Since comparison consider types, the condition returns `false`.
4. Using `regex` both left hand and right hand side values are strings hence the comparison returns `true`. `(capture using='regex' selector='\"name\": \"(.*?)\"')`

Next Steps:
1. Add notes in documentation.
2. Provide fix for the jsonpath path issue.

**Comment by shubhendumadhukar** [comment]
Added new operator `==`, this should disable strict type checking. Modifying mock as shown below would produce appropriate result.

Before
`{{#is (capture using='jsonpath' selector='$.name') 'Bob' }}`

After
`{{#is (capture using='jsonpath' selector='$.name') '==' 'Bob' }}`

Updated mock content
```
{{#is (capture using='jsonpath' selector='$.name') '==' 'Bob' }}
{
  "message": "{{capture using='jsonpath' selector='$.name'}}"
}
{{else}}
{
  "message": "Not Bob, you are: {{capture using='jsonpath' selector='$.name'}}"
}
{{/is}}
```
Change would be available in next release
