### ISSUE TITLE
type error on new validation

### ISSUE THREAD

**Issue by nazaninroozbahani** [testinggospels/camouflage#202]
Hi, thanks for camouflage as an awsome mocking tool.
from 25 october 2022 I got this error, when using camouflage through docker-compose.

![image](https://user-images.githubusercontent.com/65643735/197990921-1cd54705-48c9-4b8b-995c-d38dfca971b8.png)

**Comment by roozbahani92** [comment]
backup:
  cron: 0 * * * *
  enable: false
cache:
  enable: false
  ttl_seconds: 300
cpus: 1
ext_helpers: ./custom_handlebar.json
injection:
  enable: false
loglevel: debug
monitoring:
  port: 5555
origins:
  - http://127.0.0.1:3000
  - http://localhost:3000
protocols:
  grpc:
    enable: true
    host: 0.0.0.0
    mocks_dir: ./grpc/mocks
    port: 4312
    protos_dir: ./grpc/protos
  http:
    enable: true
    mocks_dir: ./http/mocks
    port: 8080
  http2:
    enable: false
    port: 8081
  https:
    enable: false
    port: 8443
  thrift:
    enable: false
    mocks_dir: ./thrift/mocks
    services:
      - handlers:
          - add
          - substract
          - ping
        port: 9999
        service: /opt/gen-nodejs/Calculator
  ws:
    enable: false
    mocks_dir: ./ws/mocks
    port: 8082
ssl:
  cert: ./certs/server.cert
  key: ./certs/server.key

**Comment by shubhendumadhukar** [comment]
fixed in [da23c41](https://github.com/testinggospels/camouflage/commit/da23c410aaee27700ec9e9f01b0c3ddc467e34aa)

**Comment by roozbahani92** [comment]
Unfortunately, it still is not working and is unhealthy...

**Comment by roozbahani92** [comment]
it's working now with:

validation:
  enable: false

 thanks a lot

**Comment by shubhendumadhukar** [comment]
Please continue to use version @0.9.0 in your dockerfile for now. Fix is in place, It'll be resolved where the change is merged to main and a new version is released.
