### ISSUE TITLE
[Question] Would it be possible to allow async IIFEs for pg helper?

### ISSUE THREAD

**Issue by cat-ninja** [testinggospels/camouflage#225]
**Is your feature request related to a problem? Please describe.**

I'd like to run some additional queries to the database inside of the IIFE with pg helper. 
From what I see it's possible to access the `pool` variable inside of the function and perform a query using it, but the promise won't be awaited and will be resolved sometime later.

**Describe the solution you'd like**
Do you think it'll be safe to add an `await` to [this line](https://github.com/testinggospels/camouflage/blob/61da2f5d7025faf5bbc1397fb7e8bf5b90bb46fe/src/handlebar/PgHelper.ts#L37) so it'll be possible to declare async IIFEs and use `await` inside of them?

```ts
const result = await pool.query(query)
log.debug(`[POSTGRES] Query response: ${JSON.stringify(result.rows)}`)
const fn = await context.fn(this)
const code = await eval(fn);
```

**Describe alternatives you've considered**
I'm not sure whether this is the best solution so I'm totally up for any other ideas.

**Comment by shubhendumadhukar** [comment]
You should be able to use await inside any custom code now. Please install v0.14.0

**Comment by cat-ninja** [comment]
Thanks @shubhendumadhukar! I've already tested it and it works good!
