### ISSUE TITLE
Inject and code with condition on request body does not work because of API caching

### ISSUE THREAD

**Issue by kiennt23** [testinggospels/camouflage#59]
**Describe the bug**
Writing handlebars with conditional request body will always return the same response even though the request body had changed.

**To Reproduce**
1. Mock File Content 
```
HTTP/1.1 {{#inject}}(()=>{
    if (request.body['email']==='kien@gmail.com' && request.body['password']==='Password123456') {
        return '200 OK';
    } else {
        return '404 Not Found';
    }
})();{{/inject}}
Content-Type: application/json; charset=utf-8

{{#inject}}(()=>{
    if (request.body['email']==='kien@gmail.com' && request.body['password']==='Password123456') {
        return `
        {
           "full_name": "Kien Nguyen",
           "email": "kien@gmail.com",
           "created": "2021-03-05T10:25:40.680Z",
           "updated": "2021-03-05T11:16:18.389Z",
        }
        `;
    } else {
        return `
        {
            "error_code": "USER_NOT_FOUND_ERROR",
            "message": "User not found"
        }
        `;
    }
})();{{/inject}}
```
2. Folder Structure `sessions/POST.mock`
3. Error Stack Trace
```
...
```

**Expected behavior**
Should return response base on the request body

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Attach camouflage.log file

**Comment by shubhendumadhukar** [comment]
Hi @kiennt23,

Thank you for raising the bug. This however, seems to be working as expected for me. Would you be able to share a curl of the request you are making?

**Comment by shubhendumadhukar** [comment]
My apologies, I just noticed "due to caching" part.

**Comment by kiennt23** [comment]
Thanks @shubhendumadhukar for quickly fix the bug. May I know what is the timeline to release?

**Comment by shubhendumadhukar** [comment]
@kiennt23 I am planning to publish a new release tomorrow.

A word of caution in case you haven't already taken a look at the dev branch, the config.yml would have some changes. Cache and code injection both are disabled by default.

Will update this thread once changes are published.

**Comment by kiennt23** [comment]
Thanks @shubhendumadhukar for your prompt response.
